### PR TITLE
Add aws-load-balancer-eip-allocations

### PR DESCRIPTION
**Pull request by daisuke-yoshimoto**
*Issue #, if available:*

There is no documentation for `service.beta.kubernetes.io/aws-load-balancer-eip-allocations` annotation.

Here are some related issues.
* https://github.com/kubernetes/kubernetes/issues/63959
* https://github.com/kubernetes/website/pull/20906#issuecomment-647127910

*Description of changes:*

I added a description of the `service.beta.kubernetes.io/aws-load-balancer-eip-allocations` annotation.

### CODE REVIEW

**Comment by daisuke-yoshimoto** [comment]
@jimdial-aws 

I was having trouble configuring the `service.beta.kubernetes.io/aws-load-balancer-eip-allocations` annotation as it's not documented in the documentation. I have therefore created a PR for improvement. Could you please review this PR?

**Comment by daisuke-yoshimoto** [comment]
@jimdial-aws 
Could you please review this PR?

**Comment by daisuke-yoshimoto** [comment]
@vishalkg @jimdial-aws 
Could you please review this PR?

**Comment by minzhang28** [comment]
Hi is there any update on when this PR can be merged? This missing information is helpful but not available on AWS yet

**Comment by daisuke-yoshimoto** [comment]
@jimdial-aws 

Others seem to be in trouble too.  Could you please check this pr?

**Comment by jimdial-aws** [comment]
Thank you for your submission!

**Pull request merged**
