### PR TITLE
Update security-iam-awsmanpol.md

### PR DESCRIPTION
**Pull request by nguyenkndinh**
*Issue #, if available:* https://naps.amazon.com/requests/9588

*Description of changes:* In order for docs review approval and potentially deployed to prod, the doc needs to be updated to reflect the new change. (Tried with following the instruction in https://amzn-aws.slack.com/archives/C018NQTC9A4/p1604081128038000 but it seems like the [template](https://issues.amazon.com/issues/create?template=0ba80785-f245-40b5-9b10-eac9bd8492cc) no longer exists).

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jimdial-aws** [comment]
Change to a node group policy.

**Comment by nguyenkndinh** [comment]
Hello, I wasn't aware that the PR would be merged automatically. I'm actually still waiting on the same request to MVP (https://naps.amazon.com/requests/9883) before deploying my service to support the new call.

**Comment by pgasca** [comment]
@nguyenkndinh, I'm in the process of reverting the change. I will continue our communication over the SIM ticket and Slack.

**Comment by pgasca** [comment]
@nguyenkndinh confirmed over Slack that the PR didn't need to be reverted as originally thought, so the change in this PR is being kept.

**Pull request merged**
